(async () => {
    try {
        const a = 1;

        
        console.log('Hello World')
    } catch (error) {
         console.error(error)
    }
})()